<?php

use Illuminate\Database\Seeder;

class WardsTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('wards')->insert([
        	['name' => 'Bến Nghé', 'slug' => 'ben-nghe', 'district_id' => 1],
        	['name' => 'Bến Thành', 'slug' => 'ben-thanh', 'district_id' => 1],
        	['name' => 'Cầu Kho', 'slug' => 'cau-kho', 'district_id' => 1],
        	['name' => 'Cầu Ông Lãnh', 'slug' => 'cau-ong-lanh', 'district_id' => 1],
        	['name' => 'Cô Giang', 'slug' => 'co-giang', 'district_id' => 1],
        	['name' => 'Đa Kao', 'slug' => 'da-kao', 'district_id' => 1],
        	['name' => 'Nguyễn Cư Trinh', 'slug' => 'nguyen-cu-trinh', 'district_id' => 1],
        	['name' => 'Nguyễn Thái Bình', 'slug' => 'nguyen-thai-binh', 'district_id' => 1],
        	['name' => 'Phạm Ngũ Lão', 'slug' => 'pham-ngu-lao', 'district_id' => 1],
        	['name' => 'Tân Định', 'slug' => 'tan-dinh', 'district_id' => 1],

        	['name' => 'An Khánh', 'slug' => 'ben-nghe', 'district_id' => 2],
        	['name' => 'An Lợi Đông', 'slug' => 'ben-thanh', 'district_id' => 2],
        	['name' => 'An Phú', 'slug' => 'cau-kho', 'district_id' => 2],
        	['name' => 'Bình An', 'slug' => 'cau-ong-lanh', 'district_id' => 2],
        	['name' => 'Bình Khánh', 'slug' => 'co-giang', 'district_id' => 2],
        	['name' => 'Bình Trưng Đông', 'slug' => 'da-kao', 'district_id' => 2],
        	['name' => 'Bình Trưng Tây', 'slug' => 'nguyen-cu-trinh', 'district_id' => 2],
        	['name' => 'Cát Lái', 'slug' => 'nguyen-thai-binh', 'district_id' => 2],
        	['name' => 'Thạnh Mỹ Lợi', 'slug' => 'pham-ngu-lao', 'district_id' => 2],
        	['name' => 'Thảo Điền', 'slug' => 'tan-dinh', 'district_id' => 2],
        	['name' => 'Thủ Thiêm', 'slug' => 'thu-thiem', 'district_id' => 2],

            ['name' => 'Phường 1', 'slug' => 'phuong-1', 'district_id' => 3],
            ['name' => 'Phường 2', 'slug' => 'phuong-2', 'district_id' => 3],
            ['name' => 'Phường 3', 'slug' => 'phuong-3', 'district_id' => 3],
            ['name' => 'Phường 4', 'slug' => 'phuong-4', 'district_id' => 3],
            ['name' => 'Phường 5', 'slug' => 'phuong-5', 'district_id' => 3],
            ['name' => 'Phường 6', 'slug' => 'phuong-6', 'district_id' => 3],
            ['name' => 'Phường 7', 'slug' => 'phuong-7', 'district_id' => 3],
            ['name' => 'Phường 8', 'slug' => 'phuong-8', 'district_id' => 3],
            ['name' => 'Phường 9', 'slug' => 'phuong-9', 'district_id' => 3],
            ['name' => 'Phường 10', 'slug' => 'phuong-10', 'district_id' => 3],
            ['name' => 'Phường 11', 'slug' => 'phuong-11', 'district_id' => 3],
            ['name' => 'Phường 12', 'slug' => 'phuong-12', 'district_id' => 3],
            ['name' => 'Phường 13', 'slug' => 'phuong-13', 'district_id' => 3],
            ['name' => 'Phường 14', 'slug' => 'phuong-14', 'district_id' => 3],

            ['name' => 'Phường 1', 'slug' => 'phuong-1', 'district_id' => 4],
            ['name' => 'Phường 2', 'slug' => 'phuong-2', 'district_id' => 4],
            ['name' => 'Phường 3', 'slug' => 'phuong-3', 'district_id' => 4],
            ['name' => 'Phường 4', 'slug' => 'phuong-4', 'district_id' => 4],
            ['name' => 'Phường 5', 'slug' => 'phuong-5', 'district_id' => 4],
            ['name' => 'Phường 6', 'slug' => 'phuong-6', 'district_id' => 4],
            ['name' => 'Phường 8', 'slug' => 'phuong-8', 'district_id' => 4],
            ['name' => 'Phường 9', 'slug' => 'phuong-9', 'district_id' => 4],
            ['name' => 'Phường 10', 'slug' => 'phuong-10', 'district_id' => 4],
            ['name' => 'Phường 12', 'slug' => 'phuong-12', 'district_id' => 4],
            ['name' => 'Phường 13', 'slug' => 'phuong-13', 'district_id' => 4],
            ['name' => 'Phường 14', 'slug' => 'phuong-14', 'district_id' => 4],
            ['name' => 'Phường 15', 'slug' => 'phuong-15', 'district_id' => 4],
            ['name' => 'Phường 16', 'slug' => 'phuong-16', 'district_id' => 4],
            ['name' => 'Phường 18', 'slug' => 'phuong-18', 'district_id' => 4],

            ['name' => 'Phường 1', 'slug' => 'phuong-1', 'district_id' => 5],
            ['name' => 'Phường 2', 'slug' => 'phuong-2', 'district_id' => 5],
            ['name' => 'Phường 3', 'slug' => 'phuong-3', 'district_id' => 5],
            ['name' => 'Phường 4', 'slug' => 'phuong-4', 'district_id' => 5],
            ['name' => 'Phường 5', 'slug' => 'phuong-5', 'district_id' => 5],
            ['name' => 'Phường 6', 'slug' => 'phuong-6', 'district_id' => 5],
            ['name' => 'Phường 7', 'slug' => 'phuong-7', 'district_id' => 5],
            ['name' => 'Phường 8', 'slug' => 'phuong-8', 'district_id' => 5],
            ['name' => 'Phường 9', 'slug' => 'phuong-9', 'district_id' => 5],
            ['name' => 'Phường 10', 'slug' => 'phuong-10', 'district_id' => 5],
            ['name' => 'Phường 11', 'slug' => 'phuong-11', 'district_id' => 5],
            ['name' => 'Phường 12', 'slug' => 'phuong-12', 'district_id' => 5],
            ['name' => 'Phường 13', 'slug' => 'phuong-13', 'district_id' => 5],
            ['name' => 'Phường 14', 'slug' => 'phuong-14', 'district_id' => 5],
            ['name' => 'Phường 15', 'slug' => 'phuong-15', 'district_id' => 5],

            ['name' => 'Phường 1', 'slug' => 'phuong-1', 'district_id' => 6],
            ['name' => 'Phường 2', 'slug' => 'phuong-2', 'district_id' => 6],
            ['name' => 'Phường 3', 'slug' => 'phuong-3', 'district_id' => 6],
            ['name' => 'Phường 4', 'slug' => 'phuong-4', 'district_id' => 6],
            ['name' => 'Phường 5', 'slug' => 'phuong-5', 'district_id' => 6],
            ['name' => 'Phường 6', 'slug' => 'phuong-6', 'district_id' => 6],
            ['name' => 'Phường 7', 'slug' => 'phuong-7', 'district_id' => 6],
            ['name' => 'Phường 8', 'slug' => 'phuong-8', 'district_id' => 6],
            ['name' => 'Phường 9', 'slug' => 'phuong-9', 'district_id' => 6],
            ['name' => 'Phường 10', 'slug' => 'phuong-10', 'district_id' => 6],
            ['name' => 'Phường 11', 'slug' => 'phuong-11', 'district_id' => 6],
            ['name' => 'Phường 12', 'slug' => 'phuong-12', 'district_id' => 6],
            ['name' => 'Phường 13', 'slug' => 'phuong-13', 'district_id' => 6],
            ['name' => 'Phường 14', 'slug' => 'phuong-14', 'district_id' => 6], 

            ['name' => 'Phường 1', 'slug' => 'phuong-1', 'district_id' => 6],
            ['name' => 'Phường 2', 'slug' => 'phuong-2', 'district_id' => 6],
            ['name' => 'Phường 3', 'slug' => 'phuong-3', 'district_id' => 6],
            ['name' => 'Phường 4', 'slug' => 'phuong-4', 'district_id' => 6],
            ['name' => 'Phường 5', 'slug' => 'phuong-5', 'district_id' => 6],
            ['name' => 'Phường 6', 'slug' => 'phuong-6', 'district_id' => 6],
            ['name' => 'Phường 7', 'slug' => 'phuong-7', 'district_id' => 6],
            ['name' => 'Phường 8', 'slug' => 'phuong-8', 'district_id' => 6],
            ['name' => 'Phường 9', 'slug' => 'phuong-9', 'district_id' => 6],
            ['name' => 'Phường 10', 'slug' => 'phuong-10', 'district_id' => 6],
            ['name' => 'Phường 11', 'slug' => 'phuong-11', 'district_id' => 6],
            ['name' => 'Phường 12', 'slug' => 'phuong-12', 'district_id' => 6],
            ['name' => 'Phường 13', 'slug' => 'phuong-13', 'district_id' => 6],
            ['name' => 'Phường 14', 'slug' => 'phuong-14', 'district_id' => 6], 

            //HÀ NỘI

            ['name' => 'Cống Vị', 'slug' => 'cong-vi', 'district_id' => 25],
            ['name' => 'Điện Biên', 'slug' => 'dien-bien', 'district_id' => 25],
            ['name' => 'Đội Cấn', 'slug' => 'doi-can', 'district_id' => 25],
            ['name' => 'Giảng Võ', 'slug' => 'giang-vo', 'district_id' => 25],
            ['name' => 'Kim Mã', 'slug' => 'kim-ma', 'district_id' => 25],
            ['name' => 'Liễu Giai', 'slug' => 'lieu-giai', 'district_id' => 25],
            ['name' => 'Ngọc Hà', 'slug' => 'ngoc-ha', 'district_id' => 25],
            ['name' => 'Ngọc Khánh', 'slug' => 'ngoc-khanh', 'district_id' => 25],
            ['name' => 'Nguyễn Trung Trực', 'slug' => 'nguyen-trung-truc', 'district_id' => 25],
            ['name' => 'Phúc Xá', 'slug' => 'phuc-xa', 'district_id' => 25],
            ['name' => 'Quán Thánh', 'slug' => 'quan-thanh', 'district_id' => 25],
            ['name' => 'Thành Công', 'slug' => 'thanh-cong', 'district_id' => 25],
            ['name' => 'Trúc Bạch', 'slug' => 'truc-bach', 'district_id' => 25],
            ['name' => 'Vĩnh Phúc', 'slug' => 'vinh-phuc', 'district_id' => 25],

            ['name' => 'Chương Dương Độ', 'slug' => 'chuong-duong-do', 'district_id' => 26],
            ['name' => 'Cửa Đông', 'slug' => 'cua-dong', 'district_id' => 26],
            ['name' => 'Cửa Nam', 'slug' => 'cua-nam', 'district_id' => 26],
            ['name' => 'Đồng Xuân', 'slug' => 'dong-xuan', 'district_id' => 26],
            ['name' => 'Hàng Bạc', 'slug' => 'hang-bac', 'district_id' => 26],
            ['name' => 'Hàng Bài', 'slug' => 'hang-bai', 'district_id' => 26],
            ['name' => 'Hàng Bồ', 'slug' => 'hang-bo', 'district_id' => 26],
            ['name' => 'Hàng Bông', 'slug' => 'hang-bong', 'district_id' => 26],
            ['name' => 'Hàng Buồm', 'slug' => 'hang-buom', 'district_id' => 26],
            ['name' => 'Hàng Đào', 'slug' => 'hang-dao', 'district_id' => 26],
            ['name' => 'Hàng Gai', 'slug' => 'hang-gai', 'district_id' => 26],
            ['name' => 'Hàng Mã', 'slug' => 'hang-ma', 'district_id' => 26],
            ['name' => 'Hàng Trống', 'slug' => 'hang-trong', 'district_id' => 26],
            ['name' => 'Lý Thái Tổ', 'slug' => 'ly-thai-to', 'district_id' => 26],
            ['name' => 'Phan Chu Trinh', 'slug' => 'phan-chu-trinh', 'district_id' => 26],
            ['name' => 'Phúc Tân', 'slug' => 'phuc-tan', 'district_id' => 26],
            ['name' => 'Trần Hưng Đạo', 'slug' => 'tran-hung-dao', 'district_id' => 26],
            ['name' => 'Tràng Tiền', 'slug' => 'trang-tien', 'district_id' => 26],
        ]);
    }
}
